name: Socket Security Scan
run-name: Socket CLI (npm) Reachability Scan

on:
  push:
    branches: ['**']
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

concurrency:
  group: socket-scan-${{ github.ref }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  socket-security:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow committing .socket.facts.json
      pull-requests: write
      issues: write
      id-token: write  # For GitHub token authentication

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Socket CLI
        run: npm install -g socket

      - name: Install project dependencies
        run: npm install

      - name: Run Socket Reachability Scan
        env:
          SOCKET_SECURITY_API_TOKEN: ${{ secrets.SOCKET_SECURITY_API_TOKEN }}
        run: socket scan create --reach --org david-s-github .

      - name: Commit Socket Facts file
        if: success() && github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .socket.facts.json

          if git diff --staged --quiet; then
            exit 0
          fi

          git commit -m "Update socket.facts.json - $(date -u +'%Y-%m-%d %H:%M:%S UTC') [skip ci]"
          git pull --rebase origin main || git pull origin main
          git push

      - name: Upload Socket Facts artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: socket-facts
          path: ${{ github.workspace }}/.socket.facts.json
          if-no-files-found: error
          include-hidden-files: true
